services:
  ten_agent_dev:
    image: ghcr.io/ten-framework/ten_agent_build:0.7.12
    container_name: ten_agent_dev
    platform: linux/amd64
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "${GRAPH_DESIGNER_SERVER_PORT}:${GRAPH_DESIGNER_SERVER_PORT}"
      - "3001:3000"
      - 8080:8080
      - 8400-8500:8400-8500
    volumes:
      - ./:/app
      - ${LOG_PATH}:${LOG_PATH}
      - ../.vscode/:/app/.vscode
      - ../tools/pylint/.pylintrc:/tools/pylint/.pylintrc
      - ../tools/upgrade:/tools/upgrade
    working_dir: /app
    env_file:
      - .env
    command: bash -c "cd /app/agents/examples/demo/tenapp && ./scripts/install_python_deps.sh && cd /app && ./server/bin/api -tenapp_dir=/app/agents/examples/demo/tenapp"
    networks:
      - ten_agent_network
  # ten_graph_designer:
  #   image: ghcr.io/ten-framework/ten_graph_designer:4cc33b8
  #   container_name: ten_graph_designer
  #   restart: always
  #   ports:
  #     - "3001:3000"
  #   networks:
  #     - ten_agent_network
  #   environment:
  #     - TEN_DEV_SERVER_URL=http://ten_agent_dev:49483
networks:
  ten_agent_network:
    driver: bridge
